export const colors = {
  light: {
    bg: 'bg-gray-50',
    card: 'bg-white',
    lCard:'bg-yellow-300',
    cardHover: 'hover:bg-gray-50',
    text: 'text-black',
    textSecondary: 'text-gray-600',
    textTertiary: 'text-gray-500',
    border: 'border-gray-200',
    input: 'bg-white border-gray-300 text-gray-900',
    button: 'bg-black hover:bg-gray-900',
    buttonSecondary: 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    buttonTertiary: 'bg-gray-300',
    buttonText: 'text-white',
    code: 'bg-gray-100',
    shadow: 'shadow-lg shadow-gray-200/50',
  },
  dark: {
    bg: 'bg-gray-950',
    card: 'bg-gray-900',
    lCard:'bg-yellow-300',
    cardHover: 'hover:bg-gray-800',
    text: 'text-white',
    textSecondary: 'text-gray-300',
    textTertiary: 'text-gray-500',
    border: 'border-gray-800',
    input: 'bg-gray-800 border-gray-700 text-gray-100',
    button: 'bg-white',
    buttonSecondary: 'bg-gray-800 hover:bg-gray-700 text-gray-300',
    buttonTertiary: 'bg-gray-950',
    buttonText: 'text-black',
    code: 'bg-gray-800',
    shadow: 'shadow-xl shadow-black/50',
  }
};